services:
  prometheus-service:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-admin-api"
      - "--web.enable-lifecycle"
      - "--web.listen-address=0.0.0.0:9090"
    networks:
      - monitoring
  
  grafana-service:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./grafana-data:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - prometheus-service

  fastapi-service:
    build:
      context: ./
      dockerfile: ./fastapi/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    networks:
      - monitoring
    depends_on:
      - prometheus-service

  flask-service:
    build: ./flask
    container_name: flask
    ports:
      - "5000:5000"
    environment:
      - FASTAPI_URL=http://fastapi-service:8000
    networks:
      - monitoring
    depends_on:
      - fastapi-service

networks:
  monitoring:
    driver: bridge
